### ISSUE TITLE
Should work even if the IPA's file name is not the same as the Payload/*.app in it

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/steps-amazon-s3-deploy#10]
Right now it'll fail to determine the bundle ID & version for the Plist file, as it expects the IPA's file name to be the same as the .app in it:

Related lines:

* https://github.com/bitrise-io/steps-amazon-s3-deploy/blob/master/gen_plist.sh#L7
* https://github.com/bitrise-io/steps-amazon-s3-deploy/blob/master/gen_plist.sh#L9

The IPA's file name should not matter, this step should be able to work with any .ipa file name!

**Comment by godrei** [comment]
Fixed in (https://github.com/bitrise-io/steps-amazon-s3-deploy/releases/tag/3.4.0).
