### ISSUE TITLE
S3 public url PLIST and IPA URL is not accessible with HTTPs.

### ISSUE THREAD

**Issue by rkamphol** [bitrise-io/steps-amazon-s3-deploy#11]
The current format https://#{bucket_name}.s3.amazonaws.com/#{path_in_bucket} , it's create not valid HTTPs certificate when bucket name is defined with domain name format for example "example.com".
The problem is AWS certificate is issue as *.s3.amazonaws.com. Thus, example.com.s3.amazoneaws.com will be invalid certificate map URL, and it make iOS OTA download failed.

To support all bucket name format, i think the correct public url should be as below format.
https://s3-#{aws_bucket_region}.amazonaws.com/#{bucket_name}/#{path_in_bucket}

steps for produce issue.

1. create bucket in S3 with name "yourbucketname.com" in Singapore region (ap-southeast-1).
2. configure bitrise workflow with amazon-s3-deploy step.
3. test build, after build completed. Three files will be upload to S3 which are "App.dSYM.zip", "App.ipa" and "Info.plist". For my case, i upload into "build" folder.
4. Inside Info.plist, the software-package url value will be "https://yourbucketname.com.s3.amazonaws.com/build/App.ipa" which is not valid HTTPs issue by AWS.

expectation
at step 4, to make it OTA support. the script should generate url point to IPA like
https://s3-ap-southeast-1.amazonaws.com/yourbucketname.com/build/App.ipa

**Comment by godrei** [comment]
Fixed in release 3.3.0 (https://github.com/bitrise-io/steps-amazon-s3-deploy/releases/tag/3.3.0).
